name: LPC
version: '${version}'
main: org.FractalMines.
api-version: '1.21'
authors: [IcanLevitate, LPC Development]
depend: [LuckPerms]
softdepend: [PlaceholderAPI]
description: Edited version of LPC with MiniMessage and Item placeholder Supports.
website: https://fractalmines.com
commands:
  lpc:
    description: Reload the configuration.
    permission: lpc.reload
    usage: "Usage: /lpc reload"
